trigger:
  - main  

pool: Default

variables:
  dockerHubUsername: 'saranya275'
  imageName: 'saranya275/myapp1'

steps:
  - checkout: self

  - script: |
      echo "Logging in to Docker Hub..."
      echo "$(docker_passwords)" | docker login -u "saranya275" 
    displayName: 'Docker Login'

  - script: |
      docker build -t $(imageName):$(Build.BuildId) .
    displayName: 'Build Docker Image'

  - script: |
      docker push $(imageName):$(Build.BuildId)
    displayName: 'Push Docker Image'
